=== canSAS-org/1dwg/1dwg/trunk/archives/cansas-2007/common.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT SASroot (SASentry+)>
<!ATTLIST SASroot
 xml_output_version CDATA #IMPLIED
>
<!ELEMENT SASentry (SASdata,Run?,Title,Source_file?,Flux_monitor?,((Count_time_secs)|(Count_time_frames)),Q_resolution,SASsample,SASinstrument,SASprocess)>
<!ATTLIST SASentry
 name CDATA #IMPLIED
>
<!ELEMENT SASdata (Idata+)>
<!ELEMENT Idata (((Q_A-1,I_cm-1,Idev_cm-1,Qdev_A-1?)|(Q,I,Idev,Qdev?)))>
<!ELEMENT Run (#PCDATA)>
<!ELEMENT Q_A-1 (#PCDATA)>
<!ELEMENT I_cm-1 (#PCDATA)>
<!ELEMENT Idev_cm-1 (#PCDATA)>
<!ELEMENT Qdev_A-1 (#PCDATA)>
<!ELEMENT Q (#PCDATA)>
<!ATTLIST Q
 units CDATA #REQUIRED
>
<!ELEMENT I (#PCDATA)>
<!ATTLIST I
 units CDATA #REQUIRED
>
<!ELEMENT Idev (#PCDATA)>
<!ATTLIST Idev
 units CDATA #REQUIRED
>
<!ELEMENT Qdev (#PCDATA)>
<!ATTLIST Qdev
 units CDATA #REQUIRED
>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Source_file (#PCDATA)>
<!ELEMENT Flux_monitor (#PCDATA)>
<!ELEMENT Count_time_secs (#PCDATA)>
<!ELEMENT Count_time_frames (#PCDATA)>
<!ELEMENT Q_resolution (#PCDATA)>
<!ELEMENT SASsample (sample_temperature?,sample_offset_angle_deg?,sample_x_mm?,sample_y_mm?,sample_transmission?,sample_thickness_mm)>
<!ELEMENT sample_temperature (#PCDATA)>
<!ELEMENT sample_offset_angle_deg (#PCDATA)>
<!ELEMENT sample_x_mm (#PCDATA)>
<!ELEMENT sample_y_mm (#PCDATA)>
<!ELEMENT sample_transmission (#PCDATA)>
<!ELEMENT sample_thickness_mm (#PCDATA)>
<!--Can we agree on either SAScollimator -or- SAScollimation?-->
<!ELEMENT SASinstrument (SASsource,((SAScollimator)|(SAScollimation)),SASdetector)>
<!ATTLIST SASinstrument
 name CDATA #REQUIRED
>
<!ELEMENT SASsource (radiation,beam_x_mm,beam_y_mm,((wavelength_A,wavelength_spread)|(beam_shape,wavelength_min_nm,wavelength_max_nm)))>
<!ELEMENT radiation (#PCDATA)>
<!ELEMENT beam_x_mm (#PCDATA)>
<!ELEMENT beam_y_mm (#PCDATA)>
<!ELEMENT wavelength_A (#PCDATA)>
<!ELEMENT wavelength_spread (#PCDATA)>
<!ELEMENT beam_shape (#PCDATA)>
<!ELEMENT wavelength_min_nm (#PCDATA)>
<!ELEMENT wavelength_max_nm (#PCDATA)>
<!ELEMENT SAScollimator (distance_coll_m)>
<!ELEMENT SAScollimation (distance_coll_m)>
<!ELEMENT distance_coll_m (#PCDATA)>
<!--The order of SASdetector terms in ILL XML files is different than in ISIS XML files.-->
<!ELEMENT SASdetector (((distance_SD_m,x0_mm,y0_mm,pixel_x_mm,pixel_y_mm)|(offset_angle_deg,x0_cm,y0_cm,distance_SD_m,pixel_x_mm,pixel_y_mm)))>
<!ELEMENT offset_angle_deg (#PCDATA)>
<!ELEMENT distance_SD_m (#PCDATA)>
<!ELEMENT x0_cm (#PCDATA)>
<!ELEMENT x0_mm (#PCDATA)>
<!ELEMENT y0_cm (#PCDATA)>
<!ELEMENT y0_mm (#PCDATA)>
<!ELEMENT pixel_x_mm (#PCDATA)>
<!ELEMENT pixel_y_mm (#PCDATA)>
<!ELEMENT SASprocess (date,radius_min_mm?,radius_max_mm?,((radialstep_cm?)|(radialstep_mm)),sector_width_deg?,sector_orient_deg?,I_scale_factor?,SASnote_01?,SASnote_02?,SASnote_03?,SASnote_04?,SASnote*)>
<!ATTLIST SASprocess
 name CDATA #REQUIRED
>
<!ELEMENT date (#PCDATA)>
<!ELEMENT radius_min_mm (#PCDATA)>
<!ELEMENT radius_max_mm (#PCDATA)>
<!ELEMENT radialstep_cm (#PCDATA)>
<!ELEMENT radialstep_mm (#PCDATA)>
<!ELEMENT sector_width_deg (#PCDATA)>
<!ELEMENT sector_orient_deg (#PCDATA)>
<!ELEMENT I_scale_factor (#PCDATA)>
<!--There is trouble using SASnote_01, SASnote_02, SASnote_03, SASnote_04 if there are an arbitrary number of these.  Better to use zero or more SASnotes and the number attribute to provide some order to them.-->
<!ELEMENT SASnote (#PCDATA)>
<!ATTLIST SASnote
 number CDATA #IMPLIED
>
<!-- Legacy support -->
<!ELEMENT SASnote_01 (#PCDATA)>
<!ELEMENT SASnote_02 (#PCDATA)>
<!ELEMENT SASnote_03 (#PCDATA)>
<!ELEMENT SASnote_04 (#PCDATA)>

=== canSAS-org/1dwg/1dwg/archives/cansas-2007/ill_sasxml_revised.xml
<?xml version="1.0" encoding="utf-8" ?><!DOCTYPE SASroot SYSTEM "common.dtd">
<?xml-stylesheet type="text/xsl" href="dataTable.xsl"?>
<SASroot>
 <SASentry>
  <SASdata>
   <Idata><Q_A-1>   0.000000E+00 </Q_A-1><I_cm-1>   0.000000E+00 </I_cm-1><Idev_cm-1>   0.000000E+00 </Idev_cm-1><Qdev_A-1>   0.000000E+00 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   7.853982E-04 </Q_A-1><I_cm-1>   0.000000E+00 </I_cm-1><Idev_cm-1>   0.000000E+00 </Idev_cm-1><Qdev_A-1>   5.290519E-04 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   1.570796E-03 </Q_A-1><I_cm-1>   0.000000E+00 </I_cm-1><Idev_cm-1>   0.000000E+00 </Idev_cm-1><Qdev_A-1>   5.462641E-04 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   2.356194E-03 </Q_A-1><I_cm-1>   0.000000E+00 </I_cm-1><Idev_cm-1>   0.000000E+00 </Idev_cm-1><Qdev_A-1>   5.738046E-04 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   3.423113E-03 </Q_A-1><I_cm-1>  -1.013887E+01 </I_cm-1><Idev_cm-1>  -1.595304E+01 </Idev_cm-1><Qdev_A-1>   6.252376E-04 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   3.986425E-03 </Q_A-1><I_cm-1>  -1.040687E+02 </I_cm-1><Idev_cm-1>  -6.040934E+02 </Idev_cm-1><Qdev_A-1>   6.577747E-04 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   4.747937E-03 </Q_A-1><I_cm-1>   2.803847E+01 </I_cm-1><Idev_cm-1>   2.178166E+01 </Idev_cm-1><Qdev_A-1>   7.065347E-04 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   5.511106E-03 </Q_A-1><I_cm-1>   1.305283E+01 </I_cm-1><Idev_cm-1>   2.717132E+00 </Idev_cm-1><Qdev_A-1>   7.599326E-04 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   6.312272E-03 </Q_A-1><I_cm-1>   9.199719E+00 </I_cm-1><Idev_cm-1>   1.025447E+00 </Idev_cm-1><Qdev_A-1>   8.199009E-04 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   7.085647E-03 </Q_A-1><I_cm-1>   8.427243E+00 </I_cm-1><Idev_cm-1>   7.807953E-01 </Idev_cm-1><Qdev_A-1>   8.808349E-04 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   7.858813E-03 </Q_A-1><I_cm-1>   7.684547E+00 </I_cm-1><Idev_cm-1>   5.645913E-01 </Idev_cm-1><Qdev_A-1>   9.441578E-04 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   8.645013E-03 </Q_A-1><I_cm-1>   7.676375E+00 </I_cm-1><Idev_cm-1>   5.031449E-01 </Idev_cm-1><Qdev_A-1>   1.010548E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   9.420658E-03 </Q_A-1><I_cm-1>   7.693844E+00 </I_cm-1><Idev_cm-1>   4.735692E-01 </Idev_cm-1><Qdev_A-1>   1.077662E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   1.021134E-02 </Q_A-1><I_cm-1>   7.626715E+00 </I_cm-1><Idev_cm-1>   4.288891E-01 </Idev_cm-1><Qdev_A-1>   1.147435E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   1.100320E-02 </Q_A-1><I_cm-1>   7.296264E+00 </I_cm-1><Idev_cm-1>   3.833572E-01 </Idev_cm-1><Qdev_A-1>   1.218451E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   1.178024E-02 </Q_A-1><I_cm-1>   7.506202E+00 </I_cm-1><Idev_cm-1>   3.720536E-01 </Idev_cm-1><Qdev_A-1>   1.289065E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   1.257099E-02 </Q_A-1><I_cm-1>   7.551725E+00 </I_cm-1><Idev_cm-1>   3.677744E-01 </Idev_cm-1><Qdev_A-1>   1.361718E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   1.335339E-02 </Q_A-1><I_cm-1>   7.271583E+00 </I_cm-1><Idev_cm-1>   3.373113E-01 </Idev_cm-1><Qdev_A-1>   1.434273E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   1.412778E-02 </Q_A-1><I_cm-1>   6.848637E+00 </I_cm-1><Idev_cm-1>   2.879251E-01 </Idev_cm-1><Qdev_A-1>   1.506647E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   1.492401E-02 </Q_A-1><I_cm-1>   7.045397E+00 </I_cm-1><Idev_cm-1>   2.919511E-01 </Idev_cm-1><Qdev_A-1>   1.581563E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   1.571944E-02 </Q_A-1><I_cm-1>   7.026912E+00 </I_cm-1><Idev_cm-1>   2.918268E-01 </Idev_cm-1><Qdev_A-1>   1.656843E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   1.649774E-02 </Q_A-1><I_cm-1>   6.872463E+00 </I_cm-1><Idev_cm-1>   2.736902E-01 </Idev_cm-1><Qdev_A-1>   1.730871E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   1.728140E-02 </Q_A-1><I_cm-1>   6.941207E+00 </I_cm-1><Idev_cm-1>   2.709793E-01 </Idev_cm-1><Qdev_A-1>   1.805732E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   1.806783E-02 </Q_A-1><I_cm-1>   6.562048E+00 </I_cm-1><Idev_cm-1>   2.402111E-01 </Idev_cm-1><Qdev_A-1>   1.881146E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   1.884779E-02 </Q_A-1><I_cm-1>   6.836144E+00 </I_cm-1><Idev_cm-1>   2.528365E-01 </Idev_cm-1><Qdev_A-1>   1.956191E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   1.963466E-02 </Q_A-1><I_cm-1>   6.386352E+00 </I_cm-1><Idev_cm-1>   2.171626E-01 </Idev_cm-1><Qdev_A-1>   2.032127E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   2.042139E-02 </Q_A-1><I_cm-1>   6.515014E+00 </I_cm-1><Idev_cm-1>   2.278526E-01 </Idev_cm-1><Qdev_A-1>   2.108251E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   2.119991E-02 </Q_A-1><I_cm-1>   6.375016E+00 </I_cm-1><Idev_cm-1>   2.100200E-01 </Idev_cm-1><Qdev_A-1>   2.183759E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   2.199290E-02 </Q_A-1><I_cm-1>   6.398082E+00 </I_cm-1><Idev_cm-1>   2.083693E-01 </Idev_cm-1><Qdev_A-1>   2.260834E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   2.278407E-02 </Q_A-1><I_cm-1>   6.315217E+00 </I_cm-1><Idev_cm-1>   2.081712E-01 </Idev_cm-1><Qdev_A-1>   2.337881E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   2.355685E-02 </Q_A-1><I_cm-1>   5.986359E+00 </I_cm-1><Idev_cm-1>   1.865450E-01 </Idev_cm-1><Qdev_A-1>   2.413268E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   2.434466E-02 </Q_A-1><I_cm-1>   6.410161E+00 </I_cm-1><Idev_cm-1>   2.058192E-01 </Idev_cm-1><Qdev_A-1>   2.490239E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   2.513471E-02 </Q_A-1><I_cm-1>   5.729372E+00 </I_cm-1><Idev_cm-1>   1.735024E-01 </Idev_cm-1><Qdev_A-1>   2.567541E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   2.591523E-02 </Q_A-1><I_cm-1>   5.719833E+00 </I_cm-1><Idev_cm-1>   1.728524E-01 </Idev_cm-1><Qdev_A-1>   2.644009E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   2.670370E-02 </Q_A-1><I_cm-1>   5.742700E+00 </I_cm-1><Idev_cm-1>   1.680129E-01 </Idev_cm-1><Qdev_A-1>   2.721348E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   2.748693E-02 </Q_A-1><I_cm-1>   5.453211E+00 </I_cm-1><Idev_cm-1>   1.571413E-01 </Idev_cm-1><Qdev_A-1>   2.798256E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   2.826735E-02 </Q_A-1><I_cm-1>   5.355177E+00 </I_cm-1><Idev_cm-1>   1.509180E-01 </Idev_cm-1><Qdev_A-1>   2.874966E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   2.905969E-02 </Q_A-1><I_cm-1>   5.403429E+00 </I_cm-1><Idev_cm-1>   1.522365E-01 </Idev_cm-1><Qdev_A-1>   2.952918E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   2.984972E-02 </Q_A-1><I_cm-1>   4.932916E+00 </I_cm-1><Idev_cm-1>   1.346002E-01 </Idev_cm-1><Qdev_A-1>   3.030709E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   3.062632E-02 </Q_A-1><I_cm-1>   4.896323E+00 </I_cm-1><Idev_cm-1>   1.331449E-01 </Idev_cm-1><Qdev_A-1>   3.107239E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   3.141591E-02 </Q_A-1><I_cm-1>   4.899223E+00 </I_cm-1><Idev_cm-1>   1.320771E-01 </Idev_cm-1><Qdev_A-1>   3.185104E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   3.220949E-02 </Q_A-1><I_cm-1>   4.635206E+00 </I_cm-1><Idev_cm-1>   1.227799E-01 </Idev_cm-1><Qdev_A-1>   3.263416E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   3.298980E-02 </Q_A-1><I_cm-1>   4.451303E+00 </I_cm-1><Idev_cm-1>   1.151127E-01 </Idev_cm-1><Qdev_A-1>   3.340468E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   3.377144E-02 </Q_A-1><I_cm-1>   4.535063E+00 </I_cm-1><Idev_cm-1>   1.195334E-01 </Idev_cm-1><Qdev_A-1>   3.417695E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   3.455361E-02 </Q_A-1><I_cm-1>   4.148833E+00 </I_cm-1><Idev_cm-1>   1.055833E-01 </Idev_cm-1><Qdev_A-1>   3.495017E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   3.533949E-02 </Q_A-1><I_cm-1>   4.134597E+00 </I_cm-1><Idev_cm-1>   1.044251E-01 </Idev_cm-1><Qdev_A-1>   3.572745E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   3.612345E-02 </Q_A-1><I_cm-1>   3.928159E+00 </I_cm-1><Idev_cm-1>   1.000084E-01 </Idev_cm-1><Qdev_A-1>   3.650320E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   3.689906E-02 </Q_A-1><I_cm-1>   3.948881E+00 </I_cm-1><Idev_cm-1>   1.095183E-01 </Idev_cm-1><Qdev_A-1>   3.727103E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   3.768547E-02 </Q_A-1><I_cm-1>   3.732991E+00 </I_cm-1><Idev_cm-1>   1.125003E-01 </Idev_cm-1><Qdev_A-1>   3.804988E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   3.847295E-02 </Q_A-1><I_cm-1>   3.538576E+00 </I_cm-1><Idev_cm-1>   1.091457E-01 </Idev_cm-1><Qdev_A-1>   3.883009E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   3.926152E-02 </Q_A-1><I_cm-1>   3.421592E+00 </I_cm-1><Idev_cm-1>   1.153038E-01 </Idev_cm-1><Qdev_A-1>   3.961167E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   4.005116E-02 </Q_A-1><I_cm-1>   3.155872E+00 </I_cm-1><Idev_cm-1>   1.091997E-01 </Idev_cm-1><Qdev_A-1>   4.039459E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   4.083731E-02 </Q_A-1><I_cm-1>   2.918833E+00 </I_cm-1><Idev_cm-1>   1.044780E-01 </Idev_cm-1><Qdev_A-1>   4.117431E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   4.160304E-02 </Q_A-1><I_cm-1>   3.016789E+00 </I_cm-1><Idev_cm-1>   1.216358E-01 </Idev_cm-1><Qdev_A-1>   4.193400E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   4.238020E-02 </Q_A-1><I_cm-1>   2.918326E+00 </I_cm-1><Idev_cm-1>   1.229637E-01 </Idev_cm-1><Qdev_A-1>   4.270526E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   4.318456E-02 </Q_A-1><I_cm-1>   2.855160E+00 </I_cm-1><Idev_cm-1>   1.254312E-01 </Idev_cm-1><Qdev_A-1>   4.350374E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   4.398574E-02 </Q_A-1><I_cm-1>   2.591346E+00 </I_cm-1><Idev_cm-1>   1.200769E-01 </Idev_cm-1><Qdev_A-1>   4.429927E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   4.476441E-02 </Q_A-1><I_cm-1>   2.564399E+00 </I_cm-1><Idev_cm-1>   1.287962E-01 </Idev_cm-1><Qdev_A-1>   4.507265E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   4.554401E-02 </Q_A-1><I_cm-1>   2.333560E+00 </I_cm-1><Idev_cm-1>   1.212806E-01 </Idev_cm-1><Qdev_A-1>   4.584712E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   4.632942E-02 </Q_A-1><I_cm-1>   2.224146E+00 </I_cm-1><Idev_cm-1>   1.278781E-01 </Idev_cm-1><Qdev_A-1>   4.662756E-03 </Qdev_A-1></Idata>
   <Idata><Q_A-1>   4.711189E-02 </Q_A-1><I_cm-1>   2.332195E+00 </I_cm-1><Idev_cm-1>   1.505235E-01 </Idev_cm-1><Qdev_A-1>   4.740523E-03 </Qdev_A-1></Idata>
